version: "3.7"
services:
    web:
        image: getrector_org
        restart: unless-stopped
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        entrypoint: ["docker-dev-php-entrypoint"]
        command: ["apache2-foreground"]
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal"
            PHP_IDE_CONFIG: "serverName=getrector_org"
            HOST_DEMO_DIR: "${PWD}/var/demo"
            DATABASE_HOST: "mysql"
            DATABASE_USER: "root"
            DATABASE_PASSWORD: "root"
        ports:
            - "8080:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/var/www/getrector.org:delegated
        tmpfs:
            - /var/www/getrector.org/var/cache
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "getrector_org"
        volumes:
            - ./.docker/mysql-data:/var/lib/mysql
        ports:
            - "${GETRECTOR_ORG_MYSQL_PORT:-3307}:3306"

    js-watch:
        image: node:14-alpine
        restart: unless-stopped
        working_dir: /var/www/getrector.org
        volumes:
            - .:/var/www/getrector.org:delegated
        entrypoint: [""]
        command: "ash -c 'yarn install && yarn run watch'"

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8081:8080
