name: Automated Updates

on:
    schedule:
        # https://crontab.guru/every-7-days
        -   cron: "0 0 * * 0"

jobs:
    automated_updates:
        name: Automatic Updates
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build image
              run: |
                docker build . --tag image --build-arg commitHash=${{ github.sha }}
                
            - name: Warmup cache
              run: docker run -e APP_ENV=prod image bin/console cache:warmup

            - name: Doctrine schema validation
              run: docker run -e APP_ENV=prod image bin/console doctrine:schema:validate --skip-sync --ansi
