name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'Easy Coding Standard'
                        run: composer fix-cs

                    -
                        name: 'PHPStan'
                        run: composer phpstan

                    -
                        name: 'Rector'
                        run: composer rector

                    -
                        name: 'Doctrine Validate Schema'
                        run: bin/console doctrine:schema:validate --skip-sync

                    -
                        name: 'Lint Twig'
                        run: bin/console lint:twig

                    -
                        name: 'Lint YAML'
                        run: bin/console lint:yaml config

                    -
                        name: 'Lint Dependency Injection Container'
                        run: bin/console lint:container

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.run }}
