name: Daily Pull Requests Automatic Update

on:
    schedule:
        # https://crontab.guru/daily
        -   cron: "0 0 * * *"

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    daily_pull_request_automatic_update:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        run: "composer update"
                        branch: 'automated-regenerated-nodes-composer-update'

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2
                with:
                    token: ${{ secrets.ACCESS_TOKEN }}

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}

            # see https://github.com/peter-evans/create-pull-request
            -
                name: Create pull-request
                uses: peter-evans/create-pull-request@v3
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    commit-message: "[automated] ${{ matrix.actions.name }}"
                    base: 'main'
                    branch: ${{ matrix.actions.branch }}
                    title: '[automated] ${{ matrix.actions.name }}'
                    delete-branch: true
