name: Production build

on: push

jobs:
    warmup:
        name: Cache warmup
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build image
              run: |
                docker pull rector/getrector.org:latest || true
                docker build . --tag image --cache-from rector/getrector.org:latest

            - name: Warmup cache
              run: docker run -e APP_ENV=prod image bin/console cache:warmup

            - name: Doctrine schema validation
              run: docker run -e APP_ENV=prod image bin/console doctrine:schema:validate --skip-sync --ansi
