name: Production build

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    warmup:
        name: Cache warmup
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build image
              run: |
                docker build . --tag image --build-arg commitHash=${{ github.sha }}

            - name: Warmup cache
              run: docker run -e APP_ENV=prod image bin/console cache:warmup

            - name: Doctrine schema validation
              run: docker run -e APP_ENV=prod image bin/console doctrine:schema:validate --skip-sync --ansi
